name: Bavaan Integration Tests
on: [push]

jobs:
  integration-tests:
    name: Magento 2 Integration Tests
    runs-on: ubuntu-latest
    services:
      es:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        ports:
          - 9200:9200
          - 9300:9300
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping"
    env:
      MODULE_NAME: ${{ secrets.MODULE_NAME }}
      COMPOSER_NAME: ${{ secrets.COMPOSER_NAME }}
      ELASTICSEARCH: 1
    steps:
      - uses: actions/checkout@v2
      - uses: docker://bavaan/github-actions-magento-integration-tests:7.3
        env:
          MAGENTO_VERSION: '2.3.5'
      - uses: docker://bavaan/github-actions-magento-integration-tests:7.4
        env:
          MAGENTO_VERSION: '2.4.2'
