name: Bavaan Static Tests
on: [push]

jobs:
  static:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bavaan/github-actions-m2/magento-coding-standard@master
